### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by erinmr** [yuvipanda/gh-manage-invites#1]
Hi - I have my node.js vs 6.13.1 and I get the error "Unexpected token import" when I try to run the command `npx gh-manage-invites invite NASA-Openscapes yuvipanda erinmr --team 2023-mentors-community` Any ideas what might be wrong?

**Comment by yuvipanda** [comment]
I don't really have enough experience with nodejs to help debug this, @erinmr :( 

I wrote this as an experiment in JS (https://github.com/yuvipanda/gh-manage-invites#but-why-javascript), but I think it has kinda failed and I should just write it in python instead :(

**Comment by erinmr** [comment]
Hi @yuvipanda - this was my bad. On my mac locally nodejs installed a very old version (~v6). I ran this on our 2i2c hub and installed nodejs (~v20). your package worked great. I'm going to try to move folks around now :-) Thank you.

**Comment by erinmr** [comment]
Closing since we have it working!
